name: Build and deploy Python app to Azure Web App - Bluvia-backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'Bluvia-backend'
  PYTHON_VERSION: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn==20.1.0 uvicorn==0.23.2
          
          # Test imports with the class-based approach
          python -c "from bluvia.path_utils import PathUtils; print(f'Model path: {PathUtils.get_model_path()}')"

      - name: Create deployment package
        run: |
          # Create clean deployment structure
          mkdir -p deploy_package
          cp -r bluvia requirements.txt *.py deploy_package/
          
          # Create required directories
          mkdir -p deploy_package/data
          mkdir -p deploy_package/models
          
          # Ensure proper package structure
          cd deploy_package && zip -r ../release.zip . -x "*.git*" "*__pycache__*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55CFE942EA7F451786E37A50CD10AEA0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DAFF1262D58B478CA0F9A73EE268D1F3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14B7891D7ECC435EA2114A07E843944D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: release.zip
          app-settings: |
            WEBSITES_PORT=8000
            SCM_DO_BUILD_DURING_DEPLOYMENT=true
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            BLUVIA_DATA_DIR=/home/site/wwwroot/data
            BLUVIA_MODEL_PATH=/home/site/wwwroot/models/GB_model.joblib
