# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Bluvia-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'Bluvia-backend'
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  PYTHON_VERSION: '3.9'  # Changed from 3.13 for better compatibility

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Explicitly install production requirements
          pip install gunicorn uvicorn fastapi

      - name: Create deployment package
        run: |
          # Include all files except virtual env and git files
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "*.env" "*.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Add Application Settings'
        uses: azure/appservice-settings@v2
        with:
            app-name: 'Bluvia-backend'
            slot-name: 'Production'  # Remove if not using slots
            app-settings-json: |
                    [
                    {
                          "name": "PYTHON_VERSION",
                          "value": "3.9",
                          "slotSetting": false
                        }
                      {
                        "name": "WEBSITES_PORT",
                        "value": "8000",
                        "slotSetting": false
                      },
                      {
                        "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                        "value": "true",
                        "slotSetting": false
                      }
                    ]

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: release.zip
          
