name: Build and deploy Python API to Azure Web App - Bluvia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          # Try root first, fallback to backend (for transition period)
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install -r bluvia_backend/requirements.txt
          fi

      - name: Prepare deployment package
        run: |
          # Copy requirements.txt to root if not already there
          if [ ! -f requirements.txt ] && [ -f bluvia_backend/requirements.txt ]; then
            cp bluvia_backend/requirements.txt .
          fi
          zip -r release.zip bluvia_backend requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: release
          path: .

      - name: Unzip release.zip to root
        run: unzip -o release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Bluvia'
          package: .
