name: Build and deploy Python app to Azure Web App - Bluvia-backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'Bluvia-backend'
  PYTHON_VERSION: '3.9'  # Stick to stable version
  GUNICORN_CMD: 'gunicorn --bind=0.0.0.0:8000 --workers=2 --timeout=300 --worker-class=uvicorn.workers.UvicornWorker bluvia.api:app'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn==20.1.0 uvicorn==0.23.2

      - name: Create deployment package
        run: |
          # Include all necessary files
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "*.env" "*.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55CFE942EA7F451786E37A50CD10AEA0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DAFF1262D58B478CA0F9A73EE268D1F3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14B7891D7ECC435EA2114A07E843944D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: release.zip
          app-settings: |
            WEBSITES_PORT=8000
            SCM_DO_BUILD_DURING_DEPLOYMENT=true
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            GUNICORN_CMD_ARGS=--workers=2 --timeout=300 --worker-class=uvicorn.workers.UvicornWorker
            STARTUP_COMMAND=${{ env.GUNICORN_CMD }}
